---
title: 2024's 2 favorites
author: corey
date: 2025-01-01
categories:
  - lists
  - books
  - cycling
  - urbanism
editor_options: 
  markdown: 
    wrap: sentence
from: markdown+emoji
---

I expected to use this post to look back at 2024's resolutions but I opened my notebook and found the pages jumped from September 2023 to March 2024---oops!
So, I raked my Strava, Goodreads, Letterboxd, and Instagram, allowing the mushier experiences compost and leaving the hard, memorable bits remaining.
I'm indecisive so I chose 2 for each category.

### Best movie not released in 2024
Fritz Lang's *Metropolis*, [screened in 4k at the Somerville Theater on April 12](https://letterboxd.com/runkelcorey/film/metropolis/) and accompanied by Jeff Rapsis on the synthesizer for a live score.
I've seen this film twice before and always found myself lagging during the story's midsection.
As often happens, seeing it in a theater changed everything: Jeff's score brightened the dull moments and the crowd's laughter made joy out of the silly bits that didn't age well.

##### Second best
Brian De Palma's *Phantom of the Paradise*, [screened at the Brattle Theater on July 12](https://letterboxd.com/runkelcorey/film/phantom-of-the-paradise/)

### Best fiction
Jonathan Franzen's *The Corrections*, [finished on October 9](https://www.goodreads.com/review/show/6914929232)

##### Second best
Ted Chiang's *Exhalation*, [read between October 31 and November 6](https://www.goodreads.com/review/show/6721445610)

### Best creative nonfiction
Rebecca Solnit's *Orwell's Roses*, [read from January 29 to February 2](https://www.goodreads.com/review/show/5918310921).
Among other things, this book reminded me of that Nabokov quote, that there is no such thing as reading, only re-reading:

>When you encounter [old books] again, you see differently because you’re different. Some books grow, some wither upon reacquaintance, or because you’re asking different questions you find different answers. What struck me was how much lushness and beauty and pleasure are in Nineteen Eighty-Four. They’re endangered, furtive, corrupted, but they exist

##### Second best
Rebecca Solnit's *Wanderlust*, [read from December 12, 2023 to January 8](https://www.goodreads.com/review/show/5918309991). She's just so good.

### Best instructional nonfiction
Daniel Coyle's *The Culture Code*, [read from December 4 to December 7](https://www.goodreads.com/review/show/7070704101)

##### Second best
Ben Green's *The Smart Enough City*, [read from October 17 to October 21](https://www.goodreads.com/review/show/6452258093)

### Best train ride
Transport for London's Elizabeth Line, taken on November 9 and 11.
Who would think you could take a train straight from the terminal to a 10-minute walk to your hotel?

##### Second best
Barcelona to Madrid, taken on November 14

### Best meal
Pammy's? La Sala? La Orza? These were certainly the fanciest dinners I and Claire had.
However, I need to say our wedding cocktail hour on October 12: yellowtail tacos, oysters, mini lobster rolls, and **of course** bluefish paté, Puritan & Co.'s specialty.
It was a smorgasbord made all the more savory by the people around us and our joy that day.
(I love you, Claire :)

##### Second best
Michette's gargantuan pain suisse: a lode of nougat buried in a mountain of pastry.

### Best route
Island hopping in Casco Bay on August 24 and 25.
I've had more energetic endeavors (see below) but this was a triumph of trip planning: I brought together 7 people who only knew one other person and picked an activity---sea kayaking---that would be new to everyone but approachable for everyone.
Nerves were everywhere until we caught sight of the bay: clear skies and calm, blue waters forced a sigh of releief out of everyone.
The next 24 hours were all easy paddling.

##### Second best
The White Mountains' Presidential Traverse, started and finished on July 27 but the culmination of a 7-year dream.

### Best recipe
*On Vegetables*' Ratatouille and Zucchini Bread (credit Jeremy Fox) cooked on September 16, 2024.
This recipe actually took 2 days: day 1, I made the zucchini bread and Claire and I ate leftovers; I had discovered, halfway through the recipe, that the ratatouille needed 3 hours to simmer; so, on day 2, I picked up the work and ended up with something worthy of that scene in *Ratatouille* where the critic is transported to his mother's pastoral kitchen.

##### Second best
*The Farm Table Cookbook*'s Spring on a Plate (credit Julius Roberts) cooked on June 24, 2024

### Best cup of coffee
Octant Furnas' cortado, drank on November 22, 23, and 24.
I'm wary to name a luxury hotel's coffee actually great, so don't go to the Azores just for it.
Go for many other reasons, and stay at the Octant Furnas for this!

##### Second best
Ninebar Espresso's Flat White

### Best alcoholic drink
Whatever Pammy's made me on March 18.
I'm often taken by flashy words, rare[-sounding] spirits, and then wind up with a highball glass full of cough syrup.
This was different; I listened to Claire and talked with the server and drank *something* refreshing.

##### Second best
El Albero's amontillado sherry, drank on November 15.
Who knows how much this cost?
More importantly, who cares?
I could drink it every day for the rest of my life.
