---
title: American Heartbreak
author: corey
date: '2019-11-21'
categories:
  - culture
  - analysis
subtitle: ''
---

>I am the American heartbreak–

>The rock on which Freedom

>Stumped its toe–

>The great mistake

>That Jamestown made

>Long ago

>     — Langston Hughes

Whenever I try to recall this poem, I search for "Plymouth Rock poem", and freak out beacuse I can't find it for a few seconds. This is because, all along, Hughes alludes to the founding of our nation without ever saying so. He points to our founding virtue, Freedom, and asks the reader to define it---suddenly---in their head. This question calls up our national myth, of virile men casting off the oppressive British yoke, which implants in Americans a desire for revolution and newness and independence.

I find this desire each time I encounter American colonial history. There is the Massachusetts Bay colonizers, and the Virginia Company of London, more than anything else I want to race forward to 1776. American history teaching defaults to setting our cast of characters on the North American continent in order to reach revolution, with that noble end somehow justifying everything that came before (if not ethically, then morally: we suffered, and thus *deserve* Freedom). In the same way, the outposts of our frontiersmen and women served to legitimize the murder of indigenous people, conquest of Mexican territory, and deaths of our own colonizers.

While this myth may be just that, it is a powerful story that is consistently told. Hughes rides its momentum, immediately clipping America's great strides towards Freedom with the realities of chattel slavery. Nothing could be further from Freedom. But Hughes is acknowledging the promise of Freedom: one's heart can't break if it doesn't first beat. By acknowledging the promise along with its failure, Hughes ties this heartbreak inextricably to our nation's founding. This is *the* American heartbreak, bound up with the 400-year history of democracy in Jamestown. Hughes pulls us---with present tense, with reference to Jamestown, by describing something so hard, so immovable, so central to that other early colony---into the contradiction hidden in our nation's founding, and still so hidden today.
