---
title: Why I Read Career Blogs
author: Corey Runkel
date: '2022-04-09'
categories:
  - growth
  - life
  - culture
---

**tl;dr blogs are the simple roadmap to navigating your future. Read them**

A few weeks ago, I started reading first-person, career advice/journey blogs.
I had stumbled on the first one, fifty coffees, while researching personal branding, thinking I needed to work more to stand out from a crowded field of applicants with more data-science credentials than I had.
Luckily, [Kin + Carta](https://www.kinandcarta.com/en-us/)/[Cascade Data Labs](https://cascadedatalabs.com/) took a chance on me, and I'm thrilled to start as a Data Analyst there in May, thus mooting any urgent need for personal branding.
But, that first blog, and many after, have rekindled interests I had long forgotten or shunned.

[fifty coffees](http://www.fiftycoffees.com/) has so much to be jaded about.
The font---basic---the theme---HGTV rustic---the heading `MUSINGS`---gag---and the quotes---well, just read McConnaughey's *Greenlights* and you'll develop a Pavlovian eyeroll for that font.
But, boy was I being dismissive.
Worse, all these associations spelled out something a little misogynistic.^[This is something I need to unpack because I think of myself as being very open to women as supervisors, confidants, and intellects. I think it's bound up in the aesthetics of academia and, ultimately, class.]
Her words were concise^[tagline: fifty coffees to find my next thing

Goals:
 * Get out of my apartment
 * Demand discipline of myself 
 * Take photos
 * Spend time with friends
 * Write]---and I could feel her excitement bubbling through the screen.
Each of her coffees built on the last and, [after 11 coffees](http://www.fiftycoffees.com/coffees/2014/4/14/kayti-sullivan), she can spin webs of connections between life stories and lesson's she learned.

I took from fifty coffees a sense that ambition and direction would be really useful and lead to something great.
From her blog, I jumped to [Morgen Newman](http://www.fiftycoffees.com/coffees/2014/3/27/4-morgen-newman), who wrote [a blog about starting a successful spicy honey business in 30 days](https://bushwickkitchen.com/blogs/startup-journey) (and kept it up for much longer).
This was a bit like watching Masterclass: I had no sense that I myself had the resources or partners to do what they did, but I did realize that I could get there.
It was an infectious read because it forced me to understand just how much I could get done in a month and demonstrated the ol' work-smarter-not-harder truism.
It also left me with a roadmap of how to start a company, something I've been yearning for more recently after consuming:
* [The Dropout](https://www.imdb.com/title/tt10166622/)
* [this](https://twitter.com/naval/status/1002103360646823936?lang=en) twitter thread
* some Marc Andreessen [essays](https://fictivekin.github.io/pmarchive-jekyll//guide_to_career_planning_part1.html)

Again, these are all people that I would (should?) chafe at.
It's a bunch of ego-feeding.
It's people who use buzzwords because they don't have anything to say.
It's people who got fabulously rich because they got in at the ground floor, but who also don't know anything about the world outside their own building.

But, what separates these blogs from others is that they ring of experience.
It's not a Digital Content Editor, it's someone who did the thing!
And it's a view into how they answer questions that I, a career changer person, have been having, as well as questions that I haven't known enough to ask yet.
A little of it has been vicarious decisionmaking; that's when I don't want to decide a big, life-changing thing or feel like I've already passed the opportunity to do so, and get my fix by watching others do it.
And, a little of it has been prestige porn: these people have started organizations that have *changed* the existenz of people's lives; it's like the eyebrow-raising parts of a biography, all in 800 words and all written in a How-To tone.

The How-To tone does help, though.
It helps mentally understand the stakes and that what happens today sets up a foundation for tomorrow (that one's from *The Defining Decade*).
I feel like I'm growing more by reading these, like [it's a shortcut to experiencing](https://twitter.com/naval/status/1002107992018333696).
And all this helps me engage in the process as opposed to the destination, which I've been obsessed with since at least PST.
From *The Rock Warrior's Way*, I've remembered that enjoying the process is the important part and is what will feel most fulfilling at the end of the day.

