---
title: "New EngLand"
author: corey
date: 2023-05-14
categories:
  - spatial analytics
  - gis
  - new england
  - projects
  - r
editor_options: 
  markdown: 
    wrap: sentence
draft:
    true
---

I've been reading great nonfiction---Rebecca Solnit's [*River of Shadows: Eadweard Muybridge and the Technological Wild West*](https://www.goodreads.com/book/show/28054.River_of_Shadows) most recently---and am feeling the itch again to write.
The issue is finding an area to which I can contribute; not necessarily new ideas, but new applications and new perspectives.
My inclination is to blend visualizations, statistics, and my words into periodic dispatches that reveal something new about this well-trod land.

Here are a few questions I'd like to treat this summer:
1. How do reservoirs affect land prices and access to recreation?
2. Why is so much land held in quasi-public trusts and preserves?
3. How easy is it to predict fall foliage?
4. Are there any cheap homes near transit and trees?

My vision is something like a lightweight version of pudding.cool: well-structured, beautiful, and deep.
Knowing that these might take a lot of time and I already have a backlog on this blog, I'll try to take small bites and answer part of each question once a week.
First up: reservoirs.
