project:
  type: website
  output-dir: docs

website:
  title: "Corey"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/runkelcorey
      - icon: twitter
        href: https://twitter.com/platopasta
format:
  html:
    theme: morph
    css: styles.css



