project:
  type: website
  output-dir: ../runkelcorey.github.io

website:
  title: "Corey"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/runkelcorey
      - icon: twitter
        href: https://twitter.com/platopasta
format:
  html:
    theme:
      [flatly, broadsheet.scss]



