---
title: How long do actors have left?
author: corey
date: '2020-12-07'
categories:
  - film
  - culture
  - political economy
  - predictions
---

My friend Avital wrote a great essay last year about an Instagram influencer.
The publication she released it has, unfortunately, flopped, but I will give the gist.
Lil Miquela's 2.9 million followers pale in comparison to the platform's biggest stars, but she has something they do not: an endless future.
Her computer-generated skin will never age, her fun setting will never be burdened by kids or sickness or hardship.

The essay asks why, among the Zoomer clamor for authenticity, so many follow Lil Miquela's "doings".
Avital makes the obligatory genuflections toward the fact that nobody is doing real things on Instagram before digging into this issue that makes so quaint the normal Social Media is Artifice problem.^[The point of this piece is not to challenge Baudrillard. Even though we acknowledge and have learned from his book, that does not mean we can effectively combat it. His ephigraph, from Ecclesiastes, still rings true: "The simulacrum [that Lil Miquela is the faker] is never that which conceals the truth [that human Instagrammers are real]---it is the truth which conceals that there is none [both are fake]. The simulacrum is true."]

## Unnecessary fork that may interest those who have not read Jean Baudrillard
She takes Jean Baudrillard as her starting point, skip down two paragraphs to , Baudrillard who [wrote](https://web.stanford.edu/class/history34q/readings/Baudrillard/Baudrillard_Simulacra.html) in reference to Jorge Luis Borges' one-paragraph short story, "On Exactitude in Science", translated by Andrew Hurley:

>...In that  Empire, the Art of Cartography attained such Perfection that the map of a single Province occupied the entirety of a City, and the map of the Empire, the entirety of a Province.
In time, those Unconscionable Maps no longer satisfied, and the Cartographers Guilds struck a Map of the Empire whose size was that of the Empire, and which coincided point for point with it.
The following Generations, who were not so fond of the Study of Cartography as their Forebears had been, saw that that vast Map was Useless, and not without some Pitilessness was it, that they delivered it up to the Inclemencies of Sun and Winters.
In the Deserts of the West, still today, there are Tattered Ruins of that  Map, inhabited by Animals and Beggars; in all the Land there is no other Relic of the Disciplines of Geography.
—Suarez Miranda,Viajes de varones prudentes, Libro IV,Cap. XLV, Lerida, 1658

But Baudrillard inverts Borges' story.
Rather than the residents abandoning the map, they will choose it, since the real world offers so many more imperfections to be disgusted at and dreams unfulfilled.
After so many years, the map will win over the desert-bound kingdom.
We will then be left with the "desert of the real", a sort of wasteland of reality.
Instead, everything is thrown to the economically productive artifice, which in this case is Lil Miquela and her cast of computer-generated characters.

## Back to the main branch
Coming at this from a background in movies, however, I'm interested what impact CGI talent will have on the movie industry.
It occurs to me that the actor-studio relations, which have been stable since United Artists was founded in 1919, may break apart again.
Then, studios controlled actors through exclusive deals and were able to pressure talent in their off-screen lives to a greater extent than today.
Avital quotes [a marketing officer for an influencer management company](https://www.dazeddigital.com/beauty/head/article/41436/1/mixed-race-identity-cgi-influencers-lil-miquela) to explain this makes so much business sense for studios:

>When you're using regular influencers you have all the inherent risks of people living their lives; people can get DUI's, get arrested, say non PC things. You'll always have that risk. With CGI influencers you'll have a markedly better chance of that not happening.

The richest studios will be able to purchase better CGI, better ranges of motion, etc, and each successful studio will succeed by insulating itself for years (decades?) with its own signature characters, the way Disney has with its animated stars.
The studios will also be able to co-opt new politics quickly, to commodify the moment with ease.

Of course human actors won't be able to coexist.
Taking Baudrillard seriously, we should expect the current desire for authenticity to wear off at some point as viewers accept and expect computers to do the talking as they do the exploding now.
One upshot is that the incredibly beautiful star may fade (though its place will be taken by even less credible pixels) and famous human talent, to the extent it still resides in one person, will be a rangy voice or---if motion capture remains viable against pure illustration---an emotive face.
Even though it is not linear, specialization happens whenever new technologies are adopted:

1. the introduction of cinema made obsolete the need for thousands of local theater actors who could deliver lines
2. when sound was added, actors again had to deliver lines, but only once
3. the decline of the musical has meant that the best actors need never dance; and [ultra-]HD [emphasized](https://www.today.com/popculture/hd-unforgiving-actors-makeup-artists-wbna24581670) skin quality [and makeup departments].

It might take a while, but Hollywood will look even more like Broadway in its reduced size and lower pay as improved CGI routinizes talent.
Studios will be the big winners here.
But which studios?
My money's on Disney and Dreamworks (Universal), which used terrible 2019 versions of The Lion King and Cats to test the limits of believability, but no other movie houses possess the CGI chops.

There are quite a few gaming companies that do, however.
This would be a textbook version of a sector undervalued by establishment media (if not by Wall Street) swallowing a legacy media company whole. Besides, they have practice.
In the gaming landscape, studios have always been dominant. They've already resolved muddled through the ethics of fake people doing fake actions in front of real audiences.
As more and more media companies jump into VR and Oculus gains traction, there's an opportunity for reconvergence between games and film.
