---
title: Scrapping Everything, Excitedly
author: Corey Runkel
date: '2022-04-09'
categories:
  - growth
  - R
  - design
draft: true
---

Yesterday I finished designing a cohesive résumé, cover letter, and business card.
Today, I decided to scrap it all.
I learned a lot about the options available to me when compiling LaTeX, as well as some things I needed to have in place:
* open-source fonts
* QR code to my vCard
* unity between media
* the personal touch of a signature

But the design I made lacked distinctiveness.
This was made clear to me when I visited Noam Ross' [site](https://www.noamross.net/)---wow!!!
Okay, so it looks like the Claremont Review of Books, but say it isn't pretty.
I also learned that my site, this blog, had been totally overhauled to the point of unusability by the geniuses at wowchemy (what kind of name is that?).

Finally, I had some great visions last night about how I'd like my branding to look.
Here are a few:
* background, greyed out data-science visualization (perhaps a scatter w/ a fitted line?)
* more stately typographic approach not unlike Noam's
* a commissioned illustration of me doing all the things I like, but as a figure that contorts his body to the letters of my name, illustrations which are revealed by mousing over my name on the home screen^[C = top-down view of me coding?; O = bagels; R = climbing, likea figure resting on a wall; E = side-view of a gas stove?; Y = flipping the pages of a book]
[
  c = career
  o = origins
  r = recreation
  e = eating
  y = yarns
]
Roughly, these fit in two buckets.
The first is vibey, which tries to replicate the sense of me, or a sense that I would like to communicate.
The second is object-oriented, which tries to convey what I do in a memorable way.

I think I have to synthesize these?
It won't feel like me if it isn't minimal and typographically-oriented, but it also won't feel like a distinctive, Corey sandwich until I put some meat in it.
Still, I'll use LaTeX and reproducible tools throughout.
I found Apéro, a Hugo theme that, being developed by R people, should remain stable for a while.
And that RStudio is introducing a replacement for RMarkdown that would have native VSCode support; these tools will be instrumental to *maintaining* personal branding.

Why the need for personal branding?
Because, at the end of the day, I have a design itch I need to scratch.
I loved yearbook and print publishing and this is my way in.
Also, a business card can be very cool.
I'm hoping for something abstract and minimal that will still represent some stuff I do.
Use of negative space, bold colors with a lot of dark grey? You've got me.
