---
title: 3 Things I Learned from my Marathon
author: corey
date: '2019-11-16'
categories:
  - fitness
subtitle: ''
---

Let me avoid---for all our sakes---transforming my blog into a clichéd, over-exposed photo essay of my personal struggle running. That being said, I was struck, as it was impossible not to be, by several aspects of the race weekend:

1. Marathons are a fucking business. The City of Richmond anaesthetized its downtown and a good chunk of its of the scenery for this event. Unimaginably, the $100 entry fees are well-priced (at least for the marathon). Every mile brought, alternately, water, powerade, and port-a-johns or a live band. The entire day preceding was filled with events and vendors at Richmond's convention center. In addition to the requisite race shirt, medal, and very necessary blanket, the finish line included yoga sessions, beer on tap, and pizza, all included. Meeting this massive coordination of resources were runners---truly of all types---swaddled in air-wicking this and energy-conserving that. They came and came, some twenty odd thousand, the majority towing families, friends, and track clubs. As a lone runner with 4 year-old shoes, all this *baggage* was so apparent. And sometimes this baggage wanted to make itself known, with a glimmering wristwatch or suspension systems for their extraneous gear. At day's end, however, there are no shortcuts through 26.2 miles. Your \$250 Vaporfly's are no match for my ragged Kinvara 5's if my breath is measured and stride high.

2. My stride, however, was not high. This was absolutely an ordeal, if not quite of epic proportions. Due mostly to the hard shock of tarmac and my injury-diminished mileage these last few weeks, my calves began to make their presence felt about 4 miles in, which was about 10 miles earlier than I had hoped. Still, Richmond's gentle terrain kept my pretty good until mile 16, when:
  + Wind made forward progress suddenly a thing to think about, instead of do
  + My dinner finally caught up with me
Fighting these knocked me out of a stride I had found for the first time around the half-marathon mark. I made it through the next ten miles because of the runners showing me left and right how to fight, and the outstanding spectators. During my training, I probably saw a total of 200 people, most of which were at a single park in Charlottesville. Here I could not run 100 meters without a banana, a high-five, or a swig of Miller Lite. At mile 21, I heard the first call for **BEER**, and double taked, able to snake across the road to the last volunteer. That helped.

3. This was as much a marathon as it was a real estate tour. I had always drove through Monument Ave. and thought it quaint in comparison to New Orleans' St. Charles St. It turns out that is not where Richmond's wealthy live. Continue on Monument, crossing over the [freeway built to punish Black neighborhoods for school integration](https://www.oxfordscholarship.com/view/10.1093/acprof:oso/9780199977260.001.0001/acprof-9780199977260-chapter-12), and you'll enter Henrico County. There Riverview Dr. follows lazily the James, and hundred-acre estates dominate both City and County waterfronts.
