---
title: 20 Miles Later
author: corey
date: '2019-10-20'
slug: 20-miles-later
categories:
  - analysis
  - fitness
---

In 4 weeks, I'll toe the line at the VCU Health ^[Kudos to VCU for ending their practice of suing patients for non-payment! I wish the same could be said for UVA.] [Richmond Marathon](https://www.richmondmarathon.org/). This last month has seen me run consistently farther than I ever had before, so I've had to find new places to keep my legs and mind busy. At four weeks out, most marathon plans advocate for a very long run, of about 20 miles. I did it yesterday, and I'm still not sure if my calves will be ready to go *next* Saturday, let alone tomorrow!

Conveniently, Charllottesville has a [beautiful 20-mile trail](http://www.rivannatrails.org/) that circumscribes the city. All of the lands are City parks or private easements, so it tends to be corners of property and scraps of backyards, and a lot of dilapidated industry. But the isolation can be unnerving: I can count on a single hand the amount of women I have seen run alone during the 15+ hours I've spent on it. There are several sections where the trail curls and the trees lean over and I think to myself *what a wonderful place to be attacked*.

But the vast majority of the trail isn't like this. Much of the trail parallels Charlottesville's poorest neighborhoods, where residents have had to deal with me confronting a lot of my own privilege. The vast majority is me, clohtes only in 5" running shorts, a watch, and sneakers taking up space and air outside someone else's home. Here it's the lack of clothing and equipment that define my position. I have a place to store my clothing, I have the resources to clean my sweaty shorts three times a week, I don't need to bring my phone because I'm confident no one will look at me like I want their money. For a few minutes each Saturday I take in the atmosphere outside your home, leaving only the sound of my shoes pounding the trail, and my lungs heaving slightly.
